# Generated by Django 5.1.7 on 2025-05-22 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='available',
            new_name='is_available',
        ),
        migrations.RenameField(
            model_name='car',
            old_name='seats',
            new_name='num_of_seats',
        ),
    ]
